### ISSUE TITLE
PCB Diagram

### ISSUE THREAD

**Issue by lgorek** [cow77/cbpi_BrewPi_Valve#6]
Hello
Did u have pcb diagram for this project ?? Or u use ori BrewPi expansion board ? If u do please take same picture of this board and i will reproject the board. and upload diagram/

**Comment by cow77** [comment]
Hello,

My brew-system is evolving in time from Brewtroller to Ardbir controller to CraftBeerPi. Now I use a Raspberry Pi interface board specifically designed for Craftbeerpi by Terragady ([PCB 5.0).
](https://www.terragady.com/products/terragady-5-0-pcb)  
It has 1-wire on board. But I wanted a more reliable version with a driver. So I added 1-Wire® to I2C host interface by "1 Wire Pi Plus" [https://www.abelectronics.co.uk/p/60/1-wire-pi-plus](url).
Just a couple of small changes to get it inline with the BrewPi way of interfacing (without rs485).
If you need them, I can add some pictures.

And I added a OWFS plugin for CBP, so I can use OWFS.
I added a Pi Touchscreen, and put it in a housing.

Now I can just use a 1-wire connection to the outside parts of my system: 
->   1-wire temperature sensors
->   Brewpi-SSR-expansion-boards
and 
->   BrewPi-Valve-expansion-boards.

The valve control part is still experimental: not that reliable yet, sometimes it stops working.
The temp-probes and ssr's are working as expected.

**Comment by lgorek** [comment]
Hi,
Can u send me photos of your valve board with changes.

Few weeks ago I had order 5pin this ball valve, maybe in this week i will get it:
ttps://pl.aliexpress.com/item/Zaw-r-kulowy-z-nap-dem-instrukcja-funkcja-CWX-25S-z-materia-u-ze-stali-nierdzewnej/32861673546.html 
DN15 12v CR05

Now i know that i should order 5v not 12v, but i will check first thie 12v, maybe it will works fine. Is the plug to operate this ball valve partially opening the flow?  I am not sure but use PWM to control the current, so that the valve can be continuously controlled to reduce or increase the flow of liquid from CBPi. For example if give 40mA 12v the valve will be half opened. I must check it after i get one and also what electronic is inside.  

https://www.youtube.com/watch?v=7DE9tpWQPrs
https://www.youtube.com/watch?v=b75J5DIcvTU

mail : igor@bufu.pl

Best Regards

**Comment by cow77** [comment]
If you use the Brewpi expansion board you should use 12v!
On the brewpi site you can find pictures (as in the doc-part of this plugin).
The valves are in fact internal quit simple: just a motor (2-lines, polarity defines direction) and two feedback switches, one activated if fully open, the other if fully closed.

**Comment by cow77** [comment]
See README.md for pcb and schematic (copyright BrewPi!).

I should not use PWM in this case.
What I was trying to get working, was to use the feedback-switches to know how much time is needed for a full turn. Then you know after how much time you have to stop the valve (turn the bridge off) for a x percentage open valve..
But that is not working at this moment.

**Comment by lgorek** [comment]
Hello
I recived the valves in this week i will add photos how they look up inside. 
I find in web some stuff about the valve, maybe can u use it. 
[https://www.hackster.io/ThereIsNoTry/personal-home-safety-agent-2068ea](url)

![water valve subsystem](https://user-images.githubusercontent.com/24695575/51433046-6934d480-1c42-11e9-8c1b-2cc39279b50d.jpg)
